[build]
  command = "npm run build"
  publish = "./dist"
  functions = "netlify/functions"
  base = "/"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  PYTHON_VERSION = "3.9.13"
  MISE_VERBOSE = "1"
  MISE_USE_PRECOMPILED = "1"
  GIT_LFS_ENABLED = "true"
  PYTHON_RUNTIME = "python3.9"

[dev]
  publish = "."
  functions = "netlify/functions"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/main"
  to = "/uploads.html"
  status = 200

[[redirects]]
  from = "/Frame/main"
  to = "/uploads.html"
  status = 301

[[redirects]]
  from = "/Frame/*"
  to = "/:splat"
  status = 301

# Handle API endpoints
[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/uploadImage"
  status = 200

[[redirects]]
  from = "/all-comments"
  to = "/.netlify/functions/getAllComments"
  status = 200

[[redirects]]
  from = "/submit-comment"
  to = "/.netlify/functions/submitComment"
  status = 200

[[redirects]]
  from = "/get_mosaic_images.php"
  to = "/.netlify/functions/getMosaicImages"
  status = 200
  
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "react", "react-dom"]

[functions.uploadImage]
  node_version = "18"

[functions.getAllComments]
  node_version = "18"

[functions.submitComment]
  node_version = "18"

[functions.getMosaicImages]
  node_version = "18"

[functions.processImage]
  runtime = "python3.9"
  pip_requirements = "./requirements.txt"
  included_files = ["requirements.txt"]
  python_runtime = "python3.9"

[build.processing]
  skip_processing = false 