[build]
  command = "npm run build"
  publish = "./dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/main"
  to = "/uploads.html"
  status = 200

[[redirects]]
  from = "/Frame/main"
  to = "/uploads.html"
  status = 301

[[redirects]]
  from = "/Frame/*"
  to = "/:splat"
  status = 301

# Handle API endpoints
[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/uploadImage"
  status = 200

[[redirects]]
  from = "/all-comments"
  to = "/.netlify/functions/getAllComments"
  status = 200

[[redirects]]
  from = "/submit-comment"
  to = "/.netlify/functions/submitComment"
  status = 200

[[redirects]]
  from = "/get_mosaic_images.php"
  to = "/.netlify/functions/getMosaicImages"
  status = 200

[dev]
  publish = "."
  functions = "netlify/functions"
  port = 8888

[build.processing]
  skip_processing = false 